velocity_1: 400 #id1 dynamixel (Head_Yaw)          (default: 400)
velocity_2: 400 #id2 dynamixel (Head_Pitch)        (default: 400)
velocity_3: 400 #id3 dynamixel (Head_Roll)         (default: 400)
velocity_4: 200 #id4 dynamixel (R_Shoulder_Pitch)  (default: 100)
velocity_5: 200 #id5 dynamixel (L_Shoulder_Pitch)  (default: 100)
velocity_6: 200 #id6 dynamixel (R_Shoulder_Roll)   (default: 100)
velocity_7: 200 #id7 dynamixel (L_Shoulder_Roll)   (default: 100)
velocity_8: 200 #id8 dynamixel (R_Shoulder_yaw)    (default: 100)
velocity_9: 200 #id9 dynamixel (L_Shoulder_yaw)    (default: 100)
velocity_10: 200 #id10 dynamixel (R_Elbow_Pitch)   (default: 100)
velocity_11: 200 #id11 dynamixel (L_Elbow_Pitch)   (default: 100)
velocity_12: 200 #id12 dynamixel (R_Elbow_Yaw)     (default: 100)
velocity_13: 200 #id13 dynamixel (L_Elbow_Yaw)     (default: 100)
velocity_14: 200 #id14 dynamixel (R_Wrist_Pitch)   (default: 100)
velocity_15: 200 #id15 dynamixel (L_Wrist_Pitch)   (default: 100)
velocity_16: 200 #id16 dynamixel (R_Wrist_Roll)    (default: 100)
velocity_17: 200 #id17 dynamixel (L_Wrist_Roll)    (default: 100)

accel_1: 30 #id1 dynamixel (Head_Yaw)          (default: 30)
accel_2: 30 #id2 dynamixel (Head_Pitch)        (default: 30)
accel_3: 30 #id3 dynamixel (Head_Roll)         (default: 30)
accel_4: 3 #id4 dynamixel (R_Shoulder_Pitch)  (default: 2)
accel_5: 3 #id5 dynamixel (L_Shoulder_Pitch)  (default: 2)
accel_6: 3 #id6 dynamixel (R_Shoulder_Roll)   (default: 2)
accel_7: 3 #id7 dynamixel (L_Shoulder_Roll)   (default: 2)
accel_8: 3 #id8 dynamixel (R_Shoulder_yaw)    (default: 2)
accel_9: 3 #id9 dynamixel (L_Shoulder_yaw)    (default: 2)
accel_10: 3 #id10 dynamixel (R_Elbow_Pitch)   (default: 2)
accel_11: 3 #id11 dynamixel (L_Elbow_Pitch)   (default: 2)
accel_12: 3 #id12 dynamixel (R_Elbow_Yaw)     (default: 2)
accel_13: 3 #id13 dynamixel (L_Elbow_Yaw)     (default: 2)
accel_14: 3 #id14 dynamixel (R_Wrist_Pitch)   (default: 2)
accel_15: 3 #id15 dynamixel (L_Wrist_Pitch)   (default: 2)
accel_16: 2 #id16 dynamixel (R_Wrist_Roll)    (default: 2)
accel_17: 2 #id17 dynamixel (L_Wrist_Roll)    (default: 2)


#head_yaw -> head_pitch -> head_roll
#1 -> 2 -> 3

#Left_elbow_yaw -> Left_wrist_pitch -> Left_wrist_roll
#13 -> 15 -> 17

#Right_elbow_yaw -> Right_wrist_pitch -> Right_wrist_roll
#12 -> 14 -> 16

#Left_shoulder_yaw -> Left_elbow_pitch
#9 -> 11

#Right_shoulder_yaw -> Right_elbow_pitch
#8 -> 10

#Left_shoulder_pitch -> Left_shoulder_roll
#5 -> 7

#Right_shoulder_pitch -> Right_shoulder_roll
#4 -> 6
