minions_eye_base_1_x: 240                #미니언즈 눈의 기본 위치 (x축) (검정색 가장 큰 원)
minions_eye_base_1_y: 330                #미니언즈  눈의 기본 위치 (y축) (검정색 가장 큰 원)
minions_eye_major_length_1: 44           #미니언즈  눈의 장축 반지름 (검정색 가장 큰 원)
minions_eye_minor_length_1: 44           #미니언즈  눈의 단축 반지름 (검정색 가장 큰 원)
minions_eye_rotate_angle_1: 0           #미니언즈  눈의 회전 각도 (검정색 가장 큰 원)
minions_eye_r_1: 0                       #미니언즈  눈의 색상(R) (검정색 가장 큰 원)
minions_eye_g_1: 0                       #미니언즈  눈의 색상(G) (검정색 가장 큰 원)
minions_eye_b_1: 0                       #미니언즈  눈의 색상(B) (검정색 가장 큰 원)
minions_eye_thick_1: -1                  #미니언즈  눈의 굵기 (-1이면 내부 채움)

minions_eye_base_2_x: 240                #미니언즈 눈의 기본 위치 (x축) (갈색 중간 원)
minions_eye_base_2_y: 330                #미니언즈  눈의 기본 위치 (y축) (갈색 중간 원)
minions_eye_major_length_2: 40           #미니언즈  눈의 장축 반지름 (갈색 중간 원)
minions_eye_minor_length_2: 40           #미니언즈  눈의 단축 반지름 (갈색 중간 원)
minions_eye_rotate_angle_2: 0           #미니언즈  눈의 회전 각도 (갈색 중간 원)
minions_eye_r_2: 150                       #미니언즈  눈의 색상(R) (갈색 중간 원)
minions_eye_g_2: 75                       #미니언즈  눈의 색상(G) (갈색 중간 원)
minions_eye_b_2: 0                       #미니언즈  눈의 색상(B) (갈색 중간 원)
minions_eye_thick_2: -1                  #미니언즈  눈의 굵기 (-1이면 내부 채움)

minions_eye_base_3_x: 240                #미니언즈 눈의 기본 위치 (x축) (검정색 가장 작은 원)
minions_eye_base_3_y: 330                #미니언즈  눈의 기본 위치 (y축) (검정색 가장 작은 원)
minions_eye_major_length_3: 30           #미니언즈  눈의 장축 반지름 (검정색 가장 작은 원)
minions_eye_minor_length_3: 30           #미니언즈  눈의 단축 반지름 (검정색 가장 작은 원)
minions_eye_rotate_angle_3: 0           #미니언즈  눈의 회전 각도 (검정색 가장 작은 원)
minions_eye_r_3: 0                       #미니언즈  눈의 색상(R) (검정색 가장 작은 원)
minions_eye_g_3: 0                       #미니언즈  눈의 색상(G) (검정색 가장 작은 원)
minions_eye_b_3: 0                       #미니언즈  눈의 색상(B) (검정색 가장 작은 원)
minions_eye_thick_3: -1                  #미니언즈  눈의 굵기 (-1이면 내부 채움)

minions_eye_base_4_x: 230                #미니언즈 눈의 기본 위치 (x축) (광채)
minions_eye_base_4_y: 325                #미니언즈  눈의 기본 위치 (y축) (광채)
minions_eye_major_length_4: 12           #미니언즈  눈의 장축 반지름 (광채)
minions_eye_minor_length_4: 12           #미니언즈  눈의 단축 반지름 (광채)
minions_eye_rotate_angle_4: 0           #미니언즈  눈의 회전 각도 (광채)
minions_eye_r_4: 255                       #미니언즈  눈의 색상(R) (광채)
minions_eye_g_4: 255                       #미니언즈  눈의 색상(G) (광채)
minions_eye_b_4: 255                       #미니언즈  눈의 색상(B) (광채)
minions_eye_thick_4: -1                  #미니언즈  눈의 굵기 (-1이면 내부 채움)

minions_eye_moving_x_min: -50                #ui에서 실제 움직이는 eye의 x 최솟값
minions_eye_moving_x_max: 50                #ui에서 실제 움직이는 eye의 x 최댓값
minions_eye_moving_y_min: -50                #ui에서 실제 움직이는 eye의 y 최솟값
minions_eye_moving_y_max: 50                #ui에서 실제 움직이는 eye의 y 최댓값
