thomas_left_eye_base_x: 155                #왼쪽 눈의 기본 위치 (x축)
thomas_left_eye_base_y: 355                #왼쪽 눈의 기본 위치 (y축)
thomas_left_eye_major_length: 25           #왼쪽 눈의 장축 반지름
thomas_left_eye_minor_length: 25           #왼쪽 눈의 단축 반지름
thomas_left_eye_rotate_angle: 0           #왼쪽 눈의 회전 각도
thomas_left_eye_r: 0                     #왼쪽 눈의 색상(R)
thomas_left_eye_g: 0                       #왼쪽 눈의 색상(G)
thomas_left_eye_b: 0                       #왼쪽 눈의 색상(B)
thomas_left_eye_thick: -1                  #왼쪽 눈의 굵기 (-1이면 내부 채움)


thomas_right_eye_base_x: 325                #오른쪽 눈의 기본 위치 (x축)
thomas_right_eye_base_y: 355                #오른쪽 눈의 기본 위치 (y축)
thomas_right_eye_major_length: 25           #오른쪽 눈의 장축 반지름
thomas_right_eye_minor_length: 24           #오른쪽 눈의 단축 반지름
thomas_right_eye_rotate_angle: 0           #오른쪽 눈의 회전 각도
thomas_right_eye_r: 0                     #오른쪽 눈의 색상(R)
thomas_right_eye_g: 0                       #오른쪽 눈의 색상(G)
thomas_right_eye_b: 0                       #오른쪽 눈의 색상(B)
thomas_right_eye_thick: -1                  #오른쪽 눈의 굵기 (-1이면 내부 채움)

thomas_eye_tracking_x_min: -30                #unity에서 출력되는 eye의 x 최솟값
thomas_eye_tracking_x_max: 30                #unity에서 출력되는 eye의 x 최댓값
thomas_eye_tracking_y_min: -30                #unity에서 출력되는 eye의 y 최솟값
thomas_eye_tracking_y_max: 30                #unity에서 출력되는 eye의 y 최댓값

thomas_eye_moving_x_min: -25                #ui에서 실제 움직이는 eye의 x 최솟값
thomas_eye_moving_x_max: 25                #ui에서 실제 움직이는 eye의 x 최댓값
thomas_eye_moving_y_min: -25                #ui에서 실제 움직이는 eye의 y 최솟값
thomas_eye_moving_y_max: 25                #ui에서 실제 움직이는 eye의 y 최댓값

thomas_eye_blink_time: 0.1                 #ui에서 눈을 감는 시간
thomas_eye_open_time: 5                 #ui에서 눈을 뜨고 있는 시간